apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  namespace: retail-app
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "YWRtaW4="
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "UGNxUzhNZWZlVWRZaktjbA=="
