apiVersion: v1
kind: Secret
metadata:
  name: retail-db-credentials
  namespace: retail-app
type: Opaque
stringData:
  mysql-host: "bedrock-mysql.cyz6as8g24w7.us-east-1.rds.amazonaws.com"
  mysql-password: "<your-mysql-password>"
  postgres-host: "bedrock-postgres.cyz6as8g24w7.us-east-1.rds.amazonaws.com"
  postgres-password: "<your-postgres-password>"