apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: retail-app
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "ZGJhZG1pbg=="
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "d216c1pXY3VvMW1vdGtVWQ=="
